version: 2
root-markers:
  - .git/
lint-debounce: 1s
tools:
  eslint_d: &eslint_d
    lint-command: 'eslint_d -f visualstudio --stdin --stdin-filename ${INPUT}'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - "%f(%l,%c): %tarning %m"
      - "%f(%l,%c): %rror %m"
    format-command: 'eslint_d --fix-to-stdout --stdin --stdin-filename=${INPUT}'
    format-stdin: true

  json-jq: &json-jq
    lint-command: 'jq .'

  #php-phpstan: &php-phpstan
  #  lint-command: './vendor/bin/phpstan analyze --error-format raw --no-progress'

  #php-psalm: &php-psalm
  #  lint-command: './vendor/bin/psalm --output-format=emacs --no-progress'
  #  lint-formats:
  #    - '%f:%l:%c:%trror - %m'
  #    - '%f:%l:%c:%tarning - %m'


  #python-autopep8: &python-autopep8
  #  format-command: 'autopep8 -'
  #  format-stdin: true

  python-black: &python-black
    format-command: 'black --quiet -'
    format-stdin: true

  #python-flake8: &python-flake8
  #  lint-command: 'flake8 --stdin-display-name ${INPUT} -'
  #  lint-stdin: true
  #  lint-formats:
  #    - '%f:%l:%c: %m'

languages:
  javascript: &ecmascript
    - <<: *eslint_d
  javascriptreact: *ecmascript
  typescript: *ecmascript
  typescriptreact: *ecmascript
  #javascript.jsx: *ecmascript
  #typescript.tsx: *ecmascript

  json:
    - <<: *json-jq

  #php:
  #  - <<: *php-phpstan
  #  - <<: *php-psalm

  python:
    - <<: *python-black
    #- <<: *python-flake8
    #- <<: *python-isort
    #- <<: *python-mypy
    # - <<: *python-autopep8
    # - <<: *python-yapf
