-- vim.cmd [[
--   let g:gitgutter_map_keys = 0
--   let g:gitgutter_signs = 1
--   let g:gitgutter_sign_added = '▎'
--   let g:gitgutter_sign_modified = '▎'
--   let g:gitgutter_sign_removed = '▸'
--   let g:gitgutter_sign_removed_first_line = '▎'
--   let g:gitgutter_sign_removed_above_and_below = '▎'
--   let g:gitgutter_sign_modified_removed = '▎'
--   let g:gitgutter_sign_allow_clobber = 0
--   let g:gitgutter_sign_priority = 500
-- ]]
